// config.js
require("dotenv").config();

const CONFIG = {
  CMI: {
    TELEGRAM_BOT_TOKEN: process.env.TELEGRAM_BOT_TOKEN_CMI,
    CHANNEL_ID: process.env.TELEGRAM_CHANNEL_ID_CMI,
  },
  EPICRISE: {
    TELEGRAM_BOT_TOKEN: process.env.TELEGRAM_BOT_TOKEN_EPICRISE,
    CHANNEL_ID: process.env.TELEGRAM_CHANNEL_ID_EPICRISE,
  },
  FLASH45: {
    TELEGRAM_BOT_TOKEN: process.env.TELEGRAM_BOT_TOKEN_FLASH45,
    CHANNEL_ID: process.env.TELEGRAM_CHANNEL_ID_FLASH45,
  },
  QUICKFLIP: {
    TELEGRAM_BOT_TOKEN: process.env.TELEGRAM_BOT_TOKEN_QUICKFLIP,
    CHANNEL_ID: process.env.TELEGRAM_CHANNEL_ID_QUICKFLIP,
  },
};

module.exports = CONFIG;
